version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_DEFAULT_USER=emin
    - RABBITMQ_DEFAULT_PASS=123456
    - RABBITMQ_DEFAULT_VHOST=test
    ports:
    - '5672:5672'
    - '15672:15672'
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
      args:
        req_file: "production.txt"
    depends_on:
      - rabbitmq
      - redis
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  meter:
    build:
      context: .
      dockerfile: Dockerfile.flask
      args:
        req_file: "production.txt"
    environment:
      - MODULE_NAME=meter_app.meter
    ports:
      - '5000:80'
    depends_on:
      - rabbitmq
      - consumer
  pv:
    build:
      context: .
      dockerfile: Dockerfile.flask
      args:
        req_file: "production.txt"
    environment:
      - MODULE_NAME=pv_app.pv
    ports:
      - '5001:80'
    depends_on:
      - redis
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        req_file: "test.txt"
    command: pytest --cov=./
