FROM python:3.6-alpine

WORKDIR /app

ARG req_file

COPY ./common /app/common
COPY ./pv_app /app/pv_app
COPY ./meter_app /app/meter_app
COPY ./consumer_app /app/consumer_app

COPY ./requirements /app/requirements

RUN rm -rf /app/common/tests/__pycache__
RUN rm -rf /app/pv_app/tests/__pycache__

RUN python -m pip install --upgrade pip
RUN python -m pip install -r "./requirements/$req_file" --no-cache-dir