FROM tiangolo/meinheld-gunicorn-flask:python3.7

WORKDIR /app

ARG req_file

COPY ./common /app/common
COPY ./pv_app /app/pv_app
COPY ./meter_app /app/meter_app
COPY ./requirements /app/requirements

RUN python -m pip install --upgrade pip
RUN python -m pip install -r "./requirements/$req_file" --no-cache-dir