version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_DEFAULT_USER=emin
    - RABBITMQ_DEFAULT_PASS=123456
    - RABBITMQ_DEFAULT_VHOST=test
    ports:
    - '5672:5672'
    - '15672:15672'
  app:
    build:
      context: .
      dockerfile: DockerfileConsumer
  redis:  
    image: redis:latest
    ports:
      - '6379:6379'
  flask1:
    build:
      context: .
      dockerfile: DockerfileFlask
    environment:
    - MODULE_NAME=meter
    ports:
    - '5000:80'
  flask2:
    build:
      context: .
      dockerfile: DockerfileFlask
    environment:
      - MODULE_NAME=pv
    ports:
      - '5001:80'